<?php

declare(strict_types=1);

use App\Domain\Tournament\Input\MatchResult;
use App\Domain\Tournament\Input\TeamRef;
use App\Domain\Tournament\Standings\GroupTable;
use App\Domain\Tournament\Standings\TiebreakRules;

/*
 * Conformance vectors shared byte-for-byte with the web app (tournament-game: src/lib/standings.ts).
 * Both engines must rank these identically; a drift in either one breaks its build.
 *
 * Two sources, both under tests/Vectors/ (keep the copies identical to the web app's test-vectors/):
 *   - standings.json      hand-authored golden cases — the intended FIFA semantics, human-verified.
 *   - standings.fuzz.json GENERATED by the web app (`npm run vectors`); hundreds of random-but-
 *                         reproducible group shapes that pin this engine to the web engine across a
 *                         wide input space. Do not edit by hand — regenerate and re-copy.
 */

function loadVectorSuite(string $file): array
{
    $path = dirname(__DIR__, 3).'/Vectors/'.$file;
    $suite = json_decode(file_get_contents($path), true, flags: JSON_THROW_ON_ERROR);

    $dataset = [];
    foreach ($suite['cases'] as $case) {
        $dataset[$case['name']] = [$case];
    }

    return $dataset;
}

function assertRanksLikeVector(array $case): void
{
    $teams = array_map(
        fn (array $t) => new TeamRef($t['id'], $t['name']),
        $case['teams'],
    );

    $matches = array_map(
        fn (array $m) => new MatchResult($m['homeId'], $m['awayId'], $m['homeScore'], $m['awayScore']),
        $case['matches'],
    );

    $table = GroupTable::compute($teams, $matches, TiebreakRules::fifa(), $case['qualifyCount']);

    expect(array_map(fn ($standing) => $standing->team->id, $table))->toBe($case['expected']);
}

test('matches the shared golden standings vector', function (array $case) {
    assertRanksLikeVector($case);
})->with(fn () => loadVectorSuite('standings.json'));

test('matches the shared fuzz standings vector', function (array $case) {
    assertRanksLikeVector($case);
})->with(fn () => loadVectorSuite('standings.fuzz.json'));
